export const SIGN_IN_SELLER = "SIGN_IN_SELLER";
export const LOADING_SIGNIN_DONE = "LOADING_SIGNIN_DONE";
export const LOADING_SIGNIN = "LOADING_SIGNIN";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_ERRORS = "SET_ERRORS";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

export const UNSET_META = "UNSET_META";
export const SET_META = "SET_META";